name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_TAILSCALE_IP }}
        run: |
          tar --exclude='.git*' -czf - . | tailscale ssh root@$VPS_IP "tar -xzf - -C /var/www/ixxz.moe && chown -R caddy:caddy /var/www/ixxz.moe"
